import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from "@/app/components/layouts/Navbar";
import Footer from "@/app/components/layouts/Footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body className={inter.className}>
          <div className="dark:bg-gray-900">
            <Navbar />
            <div class="container mx-auto p-4 ">
              {children}
            </div>
              <Footer />
          </div>
      </body>
      </html>
  )
}
